### ISSUE TITLE
github-book/work は誤作成ブランチ？

### ISSUE THREAD

**Issue by Junnosuke-yasuoka** [github-book/first-pr#1201]
2019/06/08現在、GitHub実践入門の P132 の**リモートブランチの作成**で`git push origin work`するとエラーになります。
````bash
$ git push origin work
To https://github.com/hogehoge/first-pr.git
 ! [rejected]        work -> work (non-fast-forward)
error: failed to push some refs to 'https://github.com/hogehoge/first-pr.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
````
原因は、**すでに origin/work が存在する為**だと思います。多分・・・。

フォーク後に、以下の操作で回避できます。
①「4 branches」とあるリンクボタンからブランチの一覧を表示。
②「work」とあるブランチの欄の右端にある**赤いゴミ箱ボタン**を押す。

これで、自分のとこにある既存の origin/work を消すことができます。
この状態で、`git push origin work`すれば、書籍記載の通りに作業継続できます。

※消すのが怖い人へ
　ここで消すことが可能なのは、あくまで自分のとこにあるブランチなので、何か誤った操作をして他の人に影響がでることはないので、自信を持ってどうぞ。
　皆様が参照することになるフォーク元の github-book 上にある work ブランチは、権限がないので消せないから大丈夫です。
　心配な方は、github-book 上で「4 branches」をクリックしてみてください。
　一覧は表示されますが、赤いゴミ箱ボタンが表示されなくて消せないことが確認できます。

**Comment by supertat55** [comment]
2019.06.30 私も同じエラーが出て同じ方法で対処しました。

**Comment by tanakakz** [comment]
2019.10.21現在、上に同じくでした。GitHub操作の初学者学習において重要な成功体験の妨げとなるので、その躓きの原因となるgithub-book側のworkブランチは削除した方が良いと考えます。Contributorのどなたか、ご検討＆対応いただけるとありがたいです。

**Comment by Sempu-Mizuha** [comment]
@tanakakz 私はとりあえずwrite権限を持っているはずなので管理者ではありませんが対応できるところまではやってみます。怒られたらその時はその時でしょ(笑)

**Comment by Sempu-Mizuha** [comment]
@tanakakz えーと、誰かがworkにpull request出してますねぇ。これ潰さないと解決出来ません。

**Comment by Sempu-Mizuha** [comment]
あー、もう！私member権限なので会話に参加させたい新規ユーザーをグループに登録出来ない！！！

**Comment by Sempu-Mizuha** [comment]
workブランチ云々でエラーになっていた原因は以下のpull requestが原因のようですねぇ…
#1197 

@Junnosuke-yasuoka 
障害発生時の時系列の記載ありがとうございます。お陰で30分ほどで原因究明出来ました。
(てか私管理者でもなんでもないのになんでこんな事必死にやっているんだろう…)

**Comment by Sempu-Mizuha** [comment]
先ほども記載しましたが、私はmember-write権限なので新規ユーザーをContributorに入れることは出来ません…。owner権限を持っているであろう @hirocaster さんにお願いしないと無理ですねぇ。

まあ、障害起こした方にクレーム言うためだけに入れるのはおかしいので(初めてなんてそんなもんでしょ)…この件は水に流して対応できるところを全てお掃除いたします。

**Comment by Sempu-Mizuha** [comment]
#1264 邪魔なブランチを削除します。

**Comment by Sempu-Mizuha** [comment]
独断判断です。怒られたら(ry

**Comment by Sempu-Mizuha** [comment]
#1265 よくわからないブランチも消します

**Comment by Sempu-Mizuha** [comment]
下記のブランチも差分がないので消します
shoChan03-work

**Comment by Sempu-Mizuha** [comment]
お掃除完了しました。実際に動くかテストをする気は起きないので…
今後の新規ユーザーのためを思ってと気になる方は検証していただけると幸いです。

なお、今回workブランチの削除を妨げる事象の原因究明はいたしましたが、誰がgithub-book上にworkブランチを作ってしまったかまでは見てません。

私的には犯人探しなんてどうでもよくて今起きてしまった事象が今後起きないようにするためにはどうすれば良いのかの方に興味がありますからねぇ。くだらないところに力は使いません。

まあ、今回の事象は防ぐ方法はないので…とりあえずまた同じ問題が起きたら早めに気づいた方がgithub-book/workブランチを消せば良いと思います。消すのが怖ければissuesか何かでアラート出せば私みたいな命知らずが対応するかもしれませんしねー。

ではでは、横からの割り込み失礼しました。

**Comment by tanakakz** [comment]
迅速なご対応に感謝します。これで後続の方々は本件による意図せぬハマり方をせずに済みますね✨

**Comment by Sempu-Mizuha** [comment]
@tanakakz 迅速かは分かりませんけどね…。たまたま今日確認していたら気づいただけですので 😅
