### ISSUE TITLE
Not found reference page

### ISSUE THREAD

**Issue by fakestarbaby** [github-book/first-pr#20]
P.34 注5 http://blog.2310.net/archives/6 のサイトが見つからないようです :cry:

**Comment by d-ikeda** [comment]
本書の編集を担当した池田といいます。ご報告ありがとうございます。確認して改めて連絡いたします。

**Comment by d-ikeda** [comment]
@fakestarbaby 様

こちらの件回答いたします。書籍執筆当時はページが存在していたのですが、現在アクセスできなくなっているようです。本書のサポートページに補足情報を掲載させていただきました。

http://gihyo.jp/book/2014/978-4-7741-6366-6/support#supportInformation

ご指摘ありがとございます。

**Comment by tomute** [comment]
このissueはクローズ可能でしょうか？

**Comment by terum** [comment]
クローズしました。
