### ISSUE TITLE
Coverallsの設定ファイル（.coveralls.yml）の記述に関する指摘

### ISSUE THREAD

**Issue by tomute** [github-book/first-pr#69]
GitHub実践入門の第8章「Githubと連携するツールとサービス」の「8.3 Coveralls」に.coveralls.ymlの記述内容が書かれています。具体的には以下。

```
service_name: travis
repo_token: xxxxxyyyyyzzzz
```

しかしhttps://coveralls.io/docs/ruby などを見るとrepo_tokenに関して"This is only needed for repos not using a CI and should be kept secret..."等と書かれているので、Travis CIと連携する場合には不要では無いでしょうか。
また、service_nameに関しても"This can be any string, but using travis-ci or travis-pro will allow Coveralls to fetch branch data, comment on pull requests, and more."とあるので、travis-ciとかの方が例としては相応しいかと思います。

**Comment by d-ikeda** [comment]
ご報告ありがとうございます。本書の編集を担当しました。確認して再度ご連絡いたします。

**Comment by tomute** [comment]
お手数ですがよろしくお願いします。

**Comment by d-ikeda** [comment]
@tomute 様
お時間がかかってしまって申し訳ありません。こちらの確認作業が完了次第ご返事いたします。

**Comment by tomute** [comment]
はい、急ぎではないので、よろしくお願いします。

**Comment by d-ikeda** [comment]
@tomute 様
回答にお時間がかかってしまって申し訳ありません。確認したところ、ご指摘のとおりでした。ご報告ありがとうございます。後ほどサポートページに正誤情報を掲載させていただきます。

**Comment by tomute** [comment]
回答ありがとうございます。サポートページへの正誤情報の掲載よろしくお願いします。

**Comment by d-ikeda** [comment]
@tomute 様
正誤情報掲載いたしました。

http://gihyo.jp/book/2014/978-4-7741-6366-6/support#supportApology

このたびはご指摘ありがとうございます。問題なければ本issueをクローズしていただけますでしょうか。

**Comment by tomute** [comment]
正誤情報の掲載ありがとうございます。
本issueクローズします。

**Comment by d-ikeda** [comment]
ありがとうございます。回答に時間がかかってしまって申し訳ありませんでした。
